#!/bin/bash

echo "🚀 Video Downloader - Backend Deployment Setup"
echo "=============================================="
echo ""
echo "📋 Files ready for Render.com deployment:"
echo "   ✅ app.py"
echo "   ✅ requirements.txt"
echo "   ✅ runtime.txt"
echo "   ✅ Procfile"
echo "   ✅ render.yaml"
echo ""
echo "📝 Next Steps:"
echo "1. Go to https://render.com and sign up/login"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Connect your GitHub repo or upload this folder"
echo "4. Use these settings:"
echo "   - Build Command: pip install -r requirements.txt"
echo "   - Start Command: gunicorn app:app"
echo "   - Environment: Python 3"
echo "5. Click 'Create Web Service'"
echo "6. Copy your backend URL after deployment"
echo ""
echo "🔗 Your backend URL will look like:"
echo "   https://video-downloader-api-xxxx.onrender.com"
echo ""
